version: '3.8'

services:

  backend:
    container_name: shorturl_backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: mongodb
      DB_DATABASE: shorturl
      DB_USERNAME: user
      DB_PASSWORD: pass 
    ports:
      - 8000:8000
    volumes:
      - ./backend/app:/app/backend/app
      - ./backend/database:/app/backend/database
      - ./backend/routes:/app/backend/routes
      - ./backend/.env:/app/backend/.env
      - ./backend/composer.json:/app/backend/composer.json
    depends_on:
      - mongodb
    networks:
      - app

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/frontend/src
    depends_on:
      - backend
    networks:
      - app

  mongodb:
    image: bitnami/mongodb:latest
    environment:
      - MONGODB_ROOT_USER=user
      - MONGODB_ROOT_PASSWORD=pass
      - MONGODB_DISABLE_SYSTEM_LOG=true
    ports:
      - 27017:27017
    volumes:
      - mongodb:/bitnami/mongodb
    networks:
      - app

networks:

  app:
    driver: bridge

volumes:
  mongodb:
